export { default as GiftItem } from './GiftItem/GiftItem';
export { default as NewCategoryModal } from './GiftItem/NewCategoryModal';
export { default as MainCatalog } from './MainCatalog/MainCatalog';
export { default as EditMainCatalog } from './MainCatalog/EditMainCatalog';
export { default as DeleteMainCatalog } from './MainCatalog/DeleteMainCatalog';
export { default as AddMainCatalog } from './MainCatalog/AddMainCatalog';
export { default as Dishes } from './Dishes/Dishes';
export { default as EditDishes } from './Dishes/EditDishes';
export { default as Faq } from './Faq/Faq';
